<a href="https://colab.research.google.com/github/jorgenotte/TiVA/blob/main/DASHBOARD_Eurostat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install eurostat

Requirement already satisfied: eurostat in /usr/local/lib/python3.10/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from eurostat) (2.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from eurostat) (2.31.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->eurostat) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->eurostat) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->eurostat) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->eurostat) (1.25.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->eurostat) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->eurostat) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->eurostat) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->eurostat) (2024.2.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->eurostat) (1.16.0)

In [2]:
# Importar librer√≠as necesarias
import pandas as pd
import numpy as np
import eurostat

In [3]:
# Code line to obtain the values cointained in a specific variable
values = eurostat.get_par_values('nama_10_gdp', 'na_item')
values

['B1GQ',
 'B1G',
 'P3',
 'P3_S13',
 'P31_S13',
 'P32_S13',
 'P31_S14_S15',
 'P31_S14',
 'P31_S15',
 'P41',
 'P5G',
 'P51G',
 'P52_P53',
 'P52',
 'P53',
 'P6',
 'P61',
 'P62',
 'P7',
 'P71',
 'P72',
 'B11',
 'B111',
 'B112',
 'D1',
 'D11',
 'D12',
 'B2A3G',
 'D2X3',
 'D2',
 'D3',
 'D21X31',
 'D21',
 'D31',
 'YA1',
 'YA0',
 'YA2',
 'P3_P5',
 'P3_P6']

## **1. Exports of goods and services (% of GDP)**
This indicator shows the value of exports of goods and services divided by the GDP in current prices.

Exports refer to goods and services leaving a country.

In [4]:
# Variable: unit
# Value: [CP_MEUR] Current prices, million euro
# Value: [PC_GDP] Percentage of gross domestic product (GDP)

# Variable: na_item
# Value: [B1G] Value added, gross (VAB a pb)
# Value: [B1GQ] Gross domestic product at market prices (PIB a pm)
# Value: [P6] Exports of goods and services

In [5]:
data1 = eurostat.get_data_df('nama_10_gdp')
data1

,freq,unit,na_item,geo\TIME_PERIOD,1975,1976,1977,1978,1979,1980,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,A,CLV05_MEUR,B1G,AT,NaN,NaN,NaN,NaN,NaN,NaN,...,252879.7,255017.1,259996.4,266016.9,272985.2,276798.3,258800.9,267789.4,281637.3,278959.7
1,A,CLV05_MEUR,B1G,BA,NaN,NaN,NaN,NaN,NaN,NaN,...,9224.4,9358.7,9658.1,9978.2,10355.7,10650.6,10358.6,11080.5,11541.8,11752.5
2,A,CLV05_MEUR,B1G,BE,NaN,NaN,NaN,NaN,NaN,NaN,...,313684.3,320657.4,323677.5,328736.7,334655.5,342451.4,325960.4,347144.4,357824.9,363046.7
3,A,CLV05_MEUR,B1G,BG,NaN,NaN,NaN,NaN,NaN,NaN,...,25372.8,26119.5,26792.6,27671.7,28637.7,29703.4,28514.7,30803.2,32447.5,32696.8
4,A,CLV05_MEUR,B1G,CH,NaN,NaN,NaN,NaN,NaN,NaN,...,390405.6,396747.1,405030.0,410565.5,422877.6,427969.5,419196.5,441816.0,453061.4,456738.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29832,A,PYP_MNAC,YA1,PT,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-11.3,-233.8
29833,A,PYP_MNAC,YA1,RO,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29834,A,PYP_MNAC,YA1,SI,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29835,A,PYP_MNAC,YA1,UK,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29836,A,PYP_MNAC,YA1,XK,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
my_filter_1 = {'geo':'ES', 'na_item':['B1GQ','P6'], 'unit':['CP_MEUR','PC_GDP']}
data1 = eurostat.get_data_df('nama_10_gdp', filter_pars=my_filter_1)
data1

,freq,unit,na_item,geo\TIME_PERIOD,1975,1976,1977,1978,1979,1980,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,A,CP_MEUR,B1GQ,ES,None,None,None,None,None,None,...,1032608.0,1078092.0,1114420.0,1162492.0,1203859.0,1245513.0,1119010.0,1222290.0,1346377.0,1461889.0
1,A,PC_GDP,B1GQ,ES,None,None,None,None,None,None,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2,A,CP_MEUR,P6,ES,None,None,None,None,None,None,...,345593.0,362356.0,377370.0,408390.0,423097.0,434770.0,344423.0,417735.0,550319.0,569493.0
3,A,PC_GDP,P6,ES,None,None,None,None,None,None,...,33.5,33.6,33.9,35.1,35.1,34.9,30.8,34.2,40.9,39.0

In [7]:
# P6_2021 (Spain) = 417.735 / Contabilidad Nacional Anual de Espa√±a. Revisi√≥n Estad√≠stica 2019 (Tabla1 a precios corrientes)
# P6_2021 (Spain) = 378.931 / Tablas FIGARO
# COMPARAR CON TABLAS IO SPAIN

## **2. Imports of goods and services (% of GDP)**
This indicator shows the value of imports of goods and services divided by the GDP in current prices.

Imports refer to goods and services entering a country.

In [8]:
# Variable: unit
# Value: [CP_MEUR] Current prices, million euro
# Value: [PC_GDP] Percentage of gross domestic product (GDP)

# Variable: na_item
# Value: [B1G] Value added, gross (VAB a pb)
# Value: [B1GQ] Gross domestic product at market prices (PIB a pm)
# Value: [P7] Imports of goods and services

In [9]:
my_filter_2 = {'geo':'ES', 'na_item':['B1GQ','P7'], 'unit':['CP_MEUR','PC_GDP']}
data2 = eurostat.get_data_df('nama_10_gdp', filter_pars=my_filter_2)
data2

,freq,unit,na_item,geo\TIME_PERIOD,1975,1976,1977,1978,1979,1980,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,A,CP_MEUR,B1GQ,ES,None,None,None,None,None,None,...,1032608.0,1078092.0,1114420.0,1162492.0,1203859.0,1245513.0,1119010.0,1222290.0,1346377.0,1461889.0
1,A,PC_GDP,B1GQ,ES,None,None,None,None,None,None,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2,A,CP_MEUR,P7,ES,None,None,None,None,None,None,...,313606.0,329598.0,332960.0,366493.0,390410.0,398153.0,328320.0,405982.0,534006.0,509212.0
3,A,PC_GDP,P7,ES,None,None,None,None,None,None,...,30.4,30.6,29.9,31.5,32.4,32.0,29.3,33.2,39.7,34.8

In [10]:
# P7_2021 (Spain) = 405.982 (CIF) / Contabilidad Nacional Anual de Espa√±a. Revisi√≥n Estad√≠stica 2019 (Tabla1 a precios corrientes)
# P7_2021 (Spain) = 377.716 (FOB) / Tablas FIGARO
# COMPARAR CON TABLAS IO SPAIN

## **3. Export to import ratio**
This ratio shows whether a country has more exports than imports or vice versa.

In addition to giving information on trade balances (exports ‚Äì imports) this indicator has the advantage of being comparable across countries.

In [11]:
data3 = eurostat.get_data_df('egi_tr1')
data3

,freq,indic_et,geo\TIME_PERIOD,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,A,RT_EXP_IMP,AL,0.51,0.49,0.51,0.58,0.56,0.61,0.61,0.60,0.61,0.63,0.68,0.70,0.81,0.61,NaN,0.78,NaN
1,A,RT_EXP_IMP,AT,1.09,1.09,1.08,1.07,1.05,1.05,1.06,1.07,1.08,1.07,1.06,1.07,1.06,1.07,1.02,1.02,1.05
2,A,RT_EXP_IMP,BA,0.48,0.45,0.51,0.58,0.57,0.58,0.62,0.60,0.65,0.68,0.74,0.73,1.09,0.70,NaN,0.76,NaN
3,A,RT_EXP_IMP,BE,1.05,1.01,1.03,1.02,1.01,1.01,1.01,1.01,1.02,1.02,1.01,1.01,1.01,1.01,1.02,0.98,0.99
4,A,RT_EXP_IMP,BG,0.74,0.73,0.84,0.95,1.01,0.95,0.99,0.98,1.00,1.07,1.06,1.01,1.05,1.03,1.02,1.01,1.05
5,A,RT_EXP_IMP,CH,1.23,1.20,1.15,1.20,1.15,1.18,1.20,1.22,1.23,1.21,1.20,1.23,1.05,1.16,1.27,1.20,1.20
6,A,RT_EXP_IMP,CY,0.92,0.80,0.90,0.87,0.95,0.98,1.02,1.03,1.00,0.99,0.95,0.97,0.99,0.92,1.01,1.00,0.98
7,A,RT_EXP_IMP,CZ,1.04,1.03,1.07,1.05,1.06,1.07,1.08,1.08,1.08,1.11,1.10,1.09,1.09,1.11,1.04,1.00,1.08
8,A,RT_EXP_IMP,DE,1.18,1.16,1.15,1.14,1.12,1.15,1.15,1.18,1.21,1.20,1.19,1.17,1.14,1.15,1.13,1.04,1.10
9,A,RT_EXP_IMP,DK,1.06,1.07,1.11,1.16,1.14,1.12,1.14,1.14,1.14,1.14,1.15,1.11,1.14,1.13,1.13,1.18,1.16
10,A,RT_EXP_IMP,EA,1.04,1.03,1.05,1.04,1.04,1.07,1.09,1.10,1.11,1.11,1.11,1.10,1.08,1.09,1.09,1.03,1.08
11,A,RT_EXP_IMP,EE,0.88,0.94,1.09,1.09,1.07,1.02,1.03,1.05,1.05,1.06,1.06,1.05,1.06,1.01,1.00,0.99,1.01
12,A,RT_EXP_IMP,EL,0.64,0.65,0.66,0.72,0.79,0.87,0.92,0.93,1.00,0.98,0.97,0.99,0.96,0.81,0.84,0.84,0.90
13,A,RT_EXP_IMP,ES,0.81,0.83,0.95,0.95,0.99,1.05,1.11,1.08,1.08,1.10,1.09,1.06,1.09,1.05,1.04,1.04,1.12
14,A,RT_EXP_IMP,EU27_2020,NaN,NaN,1.04,1.03,1.04,1.07,1.08,1.09,1.10,1.10,1.10,1.09,1.08,1.09,1.08,1.03,1.08
15,A,RT_EXP_IMP,FI,1.12,1.09,1.06,1.03,0.98,0.97,0.98,0.97,0.99,0.97,1.01,0.97,1.01,1.01,1.01,0.95,0.99
16,A,RT_EXP_IMP,FR,0.98,0.96,0.97,0.95,0.93,0.96,0.97,0.96,0.98,0.97,0.97,0.97,0.97,0.93,0.94,0.89,0.94
17,A,RT_EXP_IMP,HR,0.84,0.83,0.90,0.99,0.99,1.01,1.01,1.04,1.05,1.06,1.05,1.03,1.00,0.85,0.98,0.93,0.97
18,A,RT_EXP_IMP,HU,1.01,1.01,1.06,1.07,1.08,1.08,1.09,1.08,1.10,1.13,1.09,1.06,1.04,1.03,1.01,0.96,1.07
19,A,RT_EXP_IMP,IE,1.11,1.11,1.17,1.19,1.22,1.20,1.22,1.20,1.31,1.15,1.34,1.30,1.11,1.20,1.43,1.37,1.33
20,A,RT_EXP_IMP,IS,0.78,0.95,1.22,1.24,1.16,1.12,1.17,1.13,1.16,1.15,1.10,1.08,1.13,0.98,0.95,0.98,1.00
21,A,RT_EXP_IMP,IT,0.99,0.97,0.97,0.93,0.94,1.04,1.09,1.11,1.11,1.12,1.10,1.09,1.11,1.14,1.09,0.96,1.04
22,A,RT_EXP_IMP,LT,0.79,0.83,0.97,0.97,0.97,1.01,1.02,1.03,0.99,1.02,1.04,1.03,1.07,1.15,1.05,0.98,1.06
23,A,RT_EXP_IMP,LU,1.22,1.20,1.24,1.23,1.22,1.20,1.20,1.18,1.17,1.18,1.18,1.21,1.21,1.22,1.20,1.20,1.17
24,A,RT_EXP_IMP,LV,0.67,0.75,0.96,0.97,0.92,0.93,0.94,0.98,0.99,1.02,1.00,0.99,0.99,1.02,0.97,0.92,0.94
25,A,RT_EXP_IMP,ME,0.50,0.43,0.53,0.59,0.66,0.64,0.67,0.67,0.69,0.64,0.64,0.64,0.96,0.43,NaN,0.69,NaN
26,A,RT_EXP_IMP,MK,0.71,0.63,0.60,0.69,0.71,0.68,0.71,0.73,0.75,0.77,0.80,0.83,0.67,0.82,0.81,0.78,NaN
27,A,RT_EXP_IMP,MT,1.00,1.00,0.99,0.99,1.01,1.03,1.04,1.09,1.07,1.10,1.16,1.17,1.11,1.09,1.10,1.08,1.13
28,A,RT_EXP_IMP,NL,1.12,1.14,1.14,1.13,1.13,1.14,1.15,1.16,1.10,1.15,1.15,1.15,1.14,1.15,1.15,1.11,1.15
29,A,RT_EXP_IMP,NO,1.45,1.58,1.41,1.39,1.45,1.48,1.38,1.30,1.17,1.05,1.09,1.17,NaN,0.99,1.43,2.04,1.45
30,A,RT_EXP_IMP,PL,0.92,0.88,0.98,0.95,0.96,0.99,1.04,1.03,1.07,1.08,1.08,1.07,1.09,1.14,1.07,1.02,1.12
31,A,RT_EXP_IMP,PT,0.80,0.76,0.80,0.80,0.89,0.99,1.03,1.01,1.02,1.03,1.02,1.00,1.01,0.95,0.93,0.95,1.02
32,A,RT_EXP_IMP,RO,0.64,0.67,0.80,0.84,0.86,0.88,0.98,0.99,0.99,0.98,0.95,0.93,0.91,0.89,0.87,0.86,0.89
33,A,RT_EXP_IMP,RS,0.57,0.57,0.66,0.73,0.72,0.72,0.83,0.84,0.87,0.91,0.88,0.86,0.70,0.84,0.87,0.86,0.93
34,A,RT_EXP_IMP,SE,1.17,1.14,1.15,1.13,1.11,1.12,1.11,1.11,1.12,1.11,1.09,1.08,1.08,1.12,1.10,1.05,1.09
35,A,RT_EXP_IMP,SI,0.98,0.97,1.03,1.02,1.03,1.06,1.08,1.11,1.12,1.13,1.13,1.13,1.11,1.13,1.07,1.02,1.09
36,A,RT_EXP_IMP,SK,0.99,0.97,0.98,0.98,0.99,1.04,1.05,1.04,1.02,1.03,1.03,1.02,1.00,1.01,0.99,0.95,1.01
37,A,RT_EXP_IMP,TR,0.81,0.84,0.97,0.80,0.73,0.83,0.79,0.86,0.90,0.88,0.85,NaN,0.84,0.88,0.99,0.89,NaN
38,A,RT_EXP_IMP,XK,NaN,0.29,0.33,0.36,0.41,0.43,0.44,0.44,0.43,0.47,0.51,0.48,0.73,0.40,0.52,0.54,NaN

In [12]:
my_filter_3 = {'geo':'ES'}
data3 = eurostat.get_data_df('egi_tr1', filter_pars=my_filter_3)
data3

,freq,indic_et,geo\TIME_PERIOD,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,A,RT_EXP_IMP,ES,0.81,0.83,0.95,0.95,0.99,1.05,1.11,1.08,1.08,1.1,1.09,1.06,1.09,1.05,1.04,1.04,1.12

## **4. Employment in multinational enterprise groups (% of total employment)**
This indicator shows the share in total employment and the number of employees and self-employed persons working in multinational enterprise (MNE) groups operating on the EU territory that are controlled by an Ultimate Controlling Institutional Unit (UCI) resident in EU and non-EU countries.

An MNE group consists of at least two enterprises active in two different countries controlled by the same UCI.

In [13]:
# Variable: unit
# Value: [MIO_‚ÄãEMP] Millions of persons employed
# Value: [PC] Percentage
# Value: [PC_‚ÄãEMP] Percentage of total employment

In [14]:
data4 = eurostat.get_data_df('egr_emp')
data4

   freq size_emp     unit geo\TIME_PERIOD   2018   2019   2020   2021   2022
0     A     0-49       PC       EU27_2020    1.5    1.6    1.6    1.7    1.6
1     A     0-49       PC  EU27_2020_EFTA    1.6    1.6    1.7    1.8    1.6
2     A  250-999       PC       EU27_2020   10.6   10.9   11.0   10.5   10.5
3     A  250-999       PC  EU27_2020_EFTA   10.6   10.9   11.0   10.5   10.5
4     A   50-249       PC       EU27_2020    5.3    5.3    5.4    5.4    5.4
5     A   50-249       PC  EU27_2020_EFTA    5.3    5.4    5.4    5.4    5.4
6     A   GE1000       PC       EU27_2020   82.5   82.2   81.9   82.3   82.5
7     A   GE1000       PC  EU27_2020_EFTA   82.5   82.1   81.9   82.3   82.5
8     A    TOTAL  MIO_EMP       EU27_2020   40.0   40.6   40.7   43.6   45.4
9     A    TOTAL  MIO_EMP  EU27_2020_EFTA   42.1   42.6   42.7   45.7   47.5
10    A    TOTAL       PC       EU27_2020  100.0  100.0  100.0  100.0  100.0
11    A    TOTAL       PC  EU27_2020_EFTA  100.0  100.0  100.0  100.0  100.0
12    A    TOTAL   PC_EMP       EU27_2020   31.0   31.0   32.0   28.0   28.0

## **5. Employment in foreign controlled enterprises (% of total employment)**
This indicator shows the share of employment of foreign-controlled enterprises in total domestic employment.

In [15]:
# Variable: nace_r2
# Value: [B-N_‚ÄãS95_‚ÄãX_‚ÄãK] Total business economy; repair of computers, personal and household goods; except financial and insurance activities

# Variable: indic_sb
# Value: [V16110] Persons employed - number

# Variable: unit
# Value: [PC_TOT] Percentage of total
# Value: [PCH_1Y] Percentage change (t/t-1)

In [16]:
data5 = eurostat.get_data_df('egi_em1')
data5

,freq,nace_r2,indic_sb,unit,geo\TIME_PERIOD,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,A,B-N_S95_X_K,V16110,PCH_1Y,AT,NaN,-2.14,1.49,5.92,1.19,2.33,2.04,1.55,2.44,2.42,0.63,-0.43,0.50,-13.43
1,A,B-N_S95_X_K,V16110,PCH_1Y,BE,NaN,NaN,NaN,0.59,-3.03,-3.38,-1.40,-0.64,-12.15,-2.84,12.92,-1.95,1.96,-15.01
2,A,B-N_S95_X_K,V16110,PCH_1Y,BG,NaN,-2.80,0.08,3.37,-1.06,2.24,11.51,-0.64,-1.55,1.54,8.07,0.55,-0.26,6.44
3,A,B-N_S95_X_K,V16110,PCH_1Y,CY,NaN,-6.44,19.92,-0.22,-13.68,13.23,1.97,18.58,-9.02,-6.08,9.16,15.67,-7.98,13.07
4,A,B-N_S95_X_K,V16110,PCH_1Y,CZ,NaN,-6.68,-0.68,3.42,-1.91,-1.02,1.34,2.26,2.94,1.49,1.00,0.31,0.22,-1.97
5,A,B-N_S95_X_K,V16110,PCH_1Y,DE,NaN,-20.56,11.50,9.15,13.34,5.74,0.19,-5.47,3.22,6.64,-0.44,1.86,6.20,-20.40
6,A,B-N_S95_X_K,V16110,PCH_1Y,DK,NaN,-9.31,0.45,13.33,-0.84,-1.40,0.77,NaN,NaN,0.42,0.46,0.70,-1.04,-7.21
7,A,B-N_S95_X_K,V16110,PCH_1Y,EE,NaN,1.66,4.39,1.49,0.14,-0.02,1.06,-0.88,-0.67,0.82,0.98,0.17,-1.47,15.24
8,A,B-N_S95_X_K,V16110,PCH_1Y,EL,NaN,NaN,NaN,NaN,NaN,2.03,1.16,8.56,-0.80,12.71,4.87,15.42,0.73,-3.44
9,A,B-N_S95_X_K,V16110,PCH_1Y,ES,NaN,-7.16,11.34,-0.38,-0.46,2.97,0.19,7.85,1.70,4.44,-0.51,4.05,5.13,-3.82
10,A,B-N_S95_X_K,V16110,PCH_1Y,EU27_2020,NaN,NaN,NaN,NaN,3.37,2.49,0.57,1.20,-0.63,6.79,1.66,1.25,-0.70,-6.88
11,A,B-N_S95_X_K,V16110,PCH_1Y,FI,NaN,-2.76,-4.21,1.22,3.61,-6.11,13.94,NaN,NaN,-1.32,3.67,3.27,2.02,4.63
12,A,B-N_S95_X_K,V16110,PCH_1Y,FR,NaN,-12.48,-0.47,0.47,-2.10,4.60,-2.77,3.44,-2.14,19.24,8.03,-10.29,NaN,NaN
13,A,B-N_S95_X_K,V16110,PCH_1Y,HR,NaN,NaN,NaN,13.47,6.17,0.39,4.99,13.77,-15.19,27.32,10.34,-4.46,-2.34,23.22
14,A,B-N_S95_X_K,V16110,PCH_1Y,HU,NaN,-6.33,2.49,4.31,0.67,-0.04,3.31,3.34,-1.10,1.57,-0.61,-3.40,-1.15,-7.42
15,A,B-N_S95_X_K,V16110,PCH_1Y,IE,NaN,-6.11,0.58,-2.11,2.72,NaN,NaN,-23.96,-53.01,159.74,19.83,-0.87,12.04,-4.63
16,A,B-N_S95_X_K,V16110,PCH_1Y,IT,NaN,-3.97,-3.37,0.86,-0.88,-1.61,4.81,2.87,2.25,1.25,4.66,4.16,1.04,1.47
17,A,B-N_S95_X_K,V16110,PCH_1Y,LT,NaN,-7.76,-3.33,7.22,4.27,4.06,5.85,3.99,3.86,3.55,2.67,-0.33,-1.03,1.20
18,A,B-N_S95_X_K,V16110,PCH_1Y,LU,NaN,NaN,7.30,1.79,-4.36,2.26,3.44,1.58,2.24,0.94,0.53,1.78,0.16,6.07
19,A,B-N_S95_X_K,V16110,PCH_1Y,LV,NaN,-9.65,-2.39,4.41,6.47,6.58,4.48,9.35,-0.51,3.41,-0.58,5.19,0.61,0.19
20,A,B-N_S95_X_K,V16110,PCH_1Y,MT,NaN,-4.70,3.98,12.25,2.63,2.78,0.12,16.99,-12.90,29.22,1.82,2.57,4.11,4.24
21,A,B-N_S95_X_K,V16110,PCH_1Y,NL,NaN,3.63,0.88,4.49,0.46,1.40,-0.41,5.67,2.97,1.71,-0.05,-2.53,2.41,-17.42
22,A,B-N_S95_X_K,V16110,PCH_1Y,NO,NaN,-4.96,3.22,3.62,2.02,1.58,8.65,-0.20,-1.01,-1.87,3.45,0.14,NaN,NaN
23,A,B-N_S95_X_K,V16110,PCH_1Y,PL,NaN,2.18,6.25,4.58,0.35,3.87,4.21,4.48,1.77,3.66,-0.65,5.23,-3.94,-0.64
24,A,B-N_S95_X_K,V16110,PCH_1Y,PT,NaN,-2.19,1.59,-0.93,-5.16,1.29,10.43,6.32,0.25,1.54,7.48,5.94,2.58,-1.04
25,A,B-N_S95_X_K,V16110,PCH_1Y,RO,NaN,-1.88,-2.01,-10.81,17.80,0.64,3.39,2.37,2.10,4.16,1.49,-2.15,1.22,-8.14
26,A,B-N_S95_X_K,V16110,PCH_1Y,SE,NaN,-6.25,-0.55,8.86,-2.22,-2.74,1.64,NaN,NaN,5.41,-0.64,-0.75,4.05,-2.81
27,A,B-N_S95_X_K,V16110,PCH_1Y,SI,NaN,-5.03,1.86,10.49,4.67,5.78,20.70,8.73,7.69,1.10,4.83,0.45,-0.41,-3.60
28,A,B-N_S95_X_K,V16110,PCH_1Y,SK,NaN,-5.92,-2.24,13.00,1.89,-17.44,17.00,6.31,9.64,0.70,-1.04,-1.36,0.93,-3.61
29,A,B-N_S95_X_K,V16110,PC_TOT,AT,18.67,18.69,18.78,19.45,19.26,19.45,19.75,19.90,20.39,20.88,21.01,20.92,21.02,18.20
30,A,B-N_S95_X_K,V16110,PC_TOT,BE,15.13,NaN,17.95,17.62,17.06,16.54,16.10,15.85,13.92,13.53,15.28,14.98,15.27,12.98
31,A,B-N_S95_X_K,V16110,PC_TOT,BG,13.17,12.91,13.69,14.34,14.41,14.80,16.29,15.99,15.74,15.98,17.27,17.37,17.32,18.44
32,A,B-N_S95_X_K,V16110,PC_TOT,CY,4.65,4.44,5.24,5.28,4.85,5.96,6.02,6.93,6.31,5.92,6.46,7.48,6.88,7.78
33,A,B-N_S95_X_K,V16110,PC_TOT,CZ,27.35,26.99,26.87,27.27,26.68,26.67,26.81,26.83,27.62,28.03,28.31,28.40,28.46,27.90
34,A,B-N_S95_X_K,V16110,PC_TOT,DE,12.03,9.13,9.92,10.29,11.59,12.22,11.66,10.84,11.19,11.93,11.88,12.10,12.85,10.23
35,A,B-N_S95_X_K,V16110,PC_TOT,DK,15.31,18.91,19.21,20.51,20.30,20.02,19.71,NaN,20.14,20.23,20.32,20.46,20.25,18.79
36,A,B-N_S95_X_K,V16110,PC_TOT,EE,35.25,35.84,37.41,37.97,38.02,38.01,38.42,38.08,37.82,38.13,38.50,38.57,21.87,25.20
37,A,B-N_S95_X_K,V16110,PC_TOT,EL,NaN,NaN,NaN,NaN,5.02,5.29,5.15,5.72,5.67,6.40,6.71,7.74,7.80,7.53
38,A,B-N_S95_X_K,V16110,PC_TOT,ES,9.13,9.26,10.60,11.08,11.53,12.27,12.20,12.62,12.83,13.40,13.34,13.88,14.59,14.03
39,A,B-N_S95_X_K,V16110,PC_TOT,EU27_2020,NaN,NaN,NaN,13.40,13.85,14.19,14.28,14.45,14.36,15.33,15.58,15.78,15.67,14.59
40,A,B-N_S95_X_K,V16110,PC_TOT,FI,15.69,15.70,15.25,15.11,15.49,15.50,16.42,NaN,16.48,16.27,16.87,17.42,17.77,18.59
41,A,B-N_S95_X_K,V16110,PC_TOT,FR,12.61,11.30,11.16,10.85,10.53,10.95,10.67,11.19,10.95,13.06,14.11,12.66,NaN,NaN
42,A,B-N_S95_X_K,V16110,PC_TOT,HR,NaN,NaN,9.75,11.52,12.60,12.73,13.32,15.31,12.98,16.53,18.24,17.43,17.02,20.97
43,A,B-N_S95_X_K,V16110,PC_TOT,HU,23.78,24.24,24.71,25.79,26.02,26.41,26.41,26.00,25.71,26.12,25.96,25.08,24.79,22.95
44,A,B-N_S95_X_K,V16110,PC_TOT,IE,21.32,22.36,23.52,22.73,23.29,NaN,25.22,18.19,8.55,22.20,26.60,26.37,29.55,28.18
45,A,B-N_S95_X_K,V16110,PC_TOT,IT,7.44,7.33,7.30,7.46,7.48,7.52,8.02,8.21,8.39,8.50,8.90,9.27,9.36,9.50
46,A,B-N_S95_X_K,V16110,PC_TOT,LT,12.45,13.92,14.21,14.68,14.73,14.74,14.90,15.09,15.67,16.23,16.66,16.61,16.43,16.63
47,A,B-N_S95_X_K,V16110,PC_TOT,LU,NaN,39.45,41.13,39.96,38.34,39.07,39.45,39.05,39.92,40.30,40.52,41.24,41.30,43.81
48,A,B-N_S95_X_K,V16110,PC_TOT,LV,15.62,17.20,17.29,18.35,18.10,18.94,18.66,19.96,19.86,20.54,20.42,21.48,21.61,21.65
49,A,B-N_S95_X_K,V16110,PC_TOT,MT,15.44,12.24,12.59,13.82,14.35,14.42,14.00,15.35,13.37,17.28,17.59,18.04,18.78,19.58
50,A,B-N_S95_X_K,V16110,PC_TOT,NL,14.02,14.99,15.38,15.91,16.02,16.29,16.27,16.77,17.27,17.56,17.55,17.11,17.52,14.47
51,A,B-N_S95_X_K,V16110,PC_TOT,NO,19.90,19.30,20.00,20.27,20.25,20.18,21.53,20.92,20.71,20.32,21.02,21.05,NaN,NaN
52,A,B-N_S95_X_K,V16110,PC_TOT,PL,22.36,22.84,24.27,25.38,25.47,26.46,27.57,28.80,29.32,30.39,30.19,31.77,20.13,20.00
53,A,B-N_S95_X_K,V16110,PC_TOT,PT,10.20,10.38,10.81,11.08,11.24,11.74,12.78,13.08,13.11,13.31,14.31,15.16,15.55,15.39
54,A,B-N_S95_X_K,V16110,PC_TOT,RO,22.22,24.35,25.40,22.01,25.81,26.00,26.89,27.07,27.64,28.79,29.22,28.59,28.94,26.58
55,A,B-N_S95_X_K,V16110,PC_TOT,SE,22.49,22.13,21.42,22.29,21.84,21.23,21.46,NaN,21.02,22.16,22.02,21.85,22.74,22.10
56,A,B-N_S95_X_K,V16110,PC_TOT,SI,12.04,11.89,12.48,14.25,15.19,16.09,19.25,20.49,22.07,22.31,23.38,23.49,23.39,22.55
57,A,B-N_S95_X_K,V16110,PC_TOT,SK,32.65,33.61,22.43,25.02,26.81,22.38,25.50,25.97,28.47,28.67,28.37,27.99,28.25,27.23

In [17]:
my_filter_5 = {'geo':'ES'}
data5 = eurostat.get_data_df('egi_em1', filter_pars=my_filter_5)
data5

,freq,nace_r2,indic_sb,unit,geo\TIME_PERIOD,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,A,B-N_S95_X_K,V16110,PCH_1Y,ES,NaN,-7.16,11.34,-0.38,-0.46,2.97,0.19,7.85,1.70,4.44,-0.51,4.05,5.13,-3.82
1,A,B-N_S95_X_K,V16110,PC_TOT,ES,9.13,9.26,10.60,11.08,11.53,12.27,12.20,12.62,12.83,13.40,13.34,13.88,14.59,14.03

## **6. Exports of goods traded in Euro as invoicing currency (% of all invoicing currencies for exports)**
This indicator shows the share of extra-EU exports invoiced in euro.

Goods are traded in a range of currencies. Trade in goods by invoicing currency (TIC data) shows, for each EU country and the EU, the share of trade value invoiced in a specific currency (or group of currencies) for trade with countries outside the EU (‚Äòextra-EU‚Äô trade). For EFTA countries, the indicator shows the share of trade in ‚Ç¨ in their international trade.

In [18]:
# Variable: sitc06
# Value: [SITC0-4A] Primary goods excluding SITC division 33 (Standard International Trade Classification)
# Value: [SITC33] Petroleum, petroleum products and related materials
# Value: [SITC5-8] Manufactured goods
# Value: [TOTAL] Total - all products

# Variable: currency
# Value: [EUR] Euro
# Value: [EU_‚ÄãOTH] National currency of EU Member States not belonging to the euro area
# Value: [OTH] Other currencies
# Value: [TOTAL] Total (all currencies)
# Value: [UNK] Unknown
# Value: [USD] US dollar

In [19]:
data6 = eurostat.get_data_df('ext_lt_invcur')
data6

,freq,unit,partner,currency,stk_flow,sitc06,geo\TIME_PERIOD,2010,2012,2014,2016,2017,2018,2019,2020,2021,2022,2023
0,A,PC,EXT_EU,EUR,EXP,SITC0-4A,AT,67.0,65.6,61.9,53.3,48.3,48.6,NaN,45.7,NaN,62.0,NaN
1,A,PC,EXT_EU,EUR,EXP,SITC0-4A,BE,92.4,85.8,53.8,60.3,NaN,61.4,63.7,46.8,NaN,60.8,62.7
2,A,PC,EXT_EU,EUR,EXP,SITC0-4A,BG,54.1,46.2,57.0,53.6,NaN,48.9,NaN,45.2,NaN,50.0,NaN
3,A,PC,EXT_EU,EUR,EXP,SITC0-4A,CY,61.4,60.7,79.1,81.5,79.0,73.9,73.5,39.5,83.6,83.8,83.6
4,A,PC,EXT_EU,EUR,EXP,SITC0-4A,CZ,59.1,66.7,58.3,60.7,60.9,60.1,NaN,50.7,NaN,56.2,57.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1955,A,PC,WORLD,USD,IMP,TOTAL,NO,27.1,25.1,25.1,22.6,NaN,24.0,24.4,23.7,NaN,27.6,NaN
1956,A,PC,WORLD,USD,IMP,TOTAL,RS,NaN,NaN,NaN,16.9,15.9,13.9,13.0,13.9,13.9,13.2,10.8
1957,A,PC,WORLD,USD,IMP,TOTAL,TR,NaN,NaN,NaN,NaN,58.1,61.0,NaN,61.0,65.1,69.8,61.5
1958,A,PC,WORLD,USD,IMP,TOTAL,UKN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.6,NaN
1959,A,PC,WORLD,USD,IMP,TOTAL,XK,NaN,NaN,NaN,NaN,NaN,16.0,17.3,13.2,14.6,16.6,NaN

In [20]:
my_filter_6 = {'geo':'ES', 'sitc06':'TOTAL', 'stk_flow':'EXP'}
data6 = eurostat.get_data_df('ext_lt_invcur', filter_pars=my_filter_6)
data6

,freq,unit,partner,currency,stk_flow,sitc06,geo\TIME_PERIOD,2010,2012,2014,2016,2017,2018,2019,2020,2021,2022,2023
0,A,PC,EXT_EU,EUR,EXP,TOTAL,ES,68.3,61.2,62.7,66.4,65.1,63.8,None,53.3,63.1,61.9,None
1,A,PC,EXT_EU,EU_OTH,EXP,TOTAL,ES,0.1,0.1,0.1,0.3,0.3,0.3,None,0.0,0.0,0.0,None
2,A,PC,EXT_EU,OTH,EXP,TOTAL,ES,3.0,3.5,4.2,5.8,5.8,5.8,None,4.8,9.5,8.8,None
3,A,PC,EXT_EU,TOTAL,EXP,TOTAL,ES,100.0,100.0,100.0,100.0,100.0,100.0,None,100.0,100.0,100.0,None
4,A,PC,EXT_EU,UNK,EXP,TOTAL,ES,NaN,NaN,NaN,NaN,NaN,NaN,None,17.1,0.2,0.0,None
5,A,PC,EXT_EU,USD,EXP,TOTAL,ES,28.6,35.3,32.9,27.5,28.8,30.1,None,24.8,27.2,29.3,None

## **7. Imports of goods traded in Euro as invoicing currency (% of all invoicing currencies for imports)**
This indicator shows the share of extra-EU imports invoiced in euro.

Goods are traded in a range of currencies. Trade in goods by invoicing currency (TIC data) shows, for each EU country and the EU, the share of trade value invoiced in a specific currency (or group of currencies) for trade with countries outside the EU (‚Äòextra-EU‚Äô trade). For EFTA countries, the indicator shows the share of trade in ‚Ç¨ in their international trade.

In [21]:
my_filter_7 = {'geo':'ES', 'sitc06':'TOTAL', 'stk_flow':'IMP'}
data7 = eurostat.get_data_df('ext_lt_invcur', filter_pars=my_filter_7)
data7

,freq,unit,partner,currency,stk_flow,sitc06,geo\TIME_PERIOD,2010,2012,2014,2016,2017,2018,2019,2020,2021,2022,2023
0,A,PC,EXT_EU,EUR,IMP,TOTAL,ES,46.7,43.9,33.3,38.4,37.5,38.1,None,37.4,38.2,37.4,None
1,A,PC,EXT_EU,EU_OTH,IMP,TOTAL,ES,0.2,0.2,0.1,0.2,0.1,0.1,None,0.0,0.0,0.0,None
2,A,PC,EXT_EU,OTH,IMP,TOTAL,ES,1.2,1.0,1.1,1.8,1.6,1.5,None,2.0,5.9,4.6,None
3,A,PC,EXT_EU,TOTAL,IMP,TOTAL,ES,100.0,100.0,100.0,100.0,100.0,100.0,None,100.0,100.0,100.0,None
4,A,PC,EXT_EU,UNK,IMP,TOTAL,ES,NaN,NaN,NaN,NaN,NaN,NaN,None,8.1,0.1,0.0,None
5,A,PC,EXT_EU,USD,IMP,TOTAL,ES,51.9,54.9,65.4,59.6,60.8,60.2,None,52.5,55.8,58.0,None

## **8. International investment position (Million euro)**
This indicator shows the difference between the investment assets and liabilities and represents either a net claim on or a net liability to the rest of the world.

The international investment position (IIP) shows at a point in time the value of financial assets of residents of an economy that are claims on nonresidents and the liabilities of residents of an economy to non-residents.

In [ ]:
# No es posible cargar esta tabla, se desconecta la sesi√≥n ('bop_iip6_q')
#data8 = eurostat.get_data_df('bop_iip6_q')
#data8

## **9. Investments in the EU by foreign investors (% of GDP)**
This indicator shows the value of the investment stocks held by multinational enterprises in the economy of the reporting country. It is divided by GDP to allow comparisons across countries.

In [24]:
# Variable: Entity
# Value: [TOTAL] Total
# Value: [NSPE] Non-special purpose entities (or Operating units)

# Variable: indic_bp
# Value: [FGDP] GDP (flows in % of GDP)
# Value: [SGDP] GDP (stocks in % of GDP)
# Value: [IPOS] Rate of return on direct investment (FDI income / FDI stocks)
# Value: [PCPOS] FDI stocks (in % of extra EU FDI stocks)
# Value: [TIFDI] Market integration - Foreign Direct Investment intensity - Average value of inward and outward Foreign Direct Investment flows divided by GDP, multiplied by 100

# Variable: fdi_item
# Value: [DO__D__F] Direct investment abroad (DIA)
# Value: [DI__D__F] Direct investment in the reporting economy (DIRE)
# Value: [NAP] Not applicable

In [25]:
data9 = eurostat.get_data_df('bop_fdi6_ind')
data9

,freq,entity,indic_bp,fdi_item,partner,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,NSPE,FGDP,DI__D__F,EXT_EU27_2020,EU27_2020,0.8,0.7,2.7,1.3,0.7,1.8,0.7,NaN,NaN,NaN
1,A,NSPE,FGDP,DI__D__F,EXT_EU28,EU28,0.9,0.5,2.1,1.6,0.4,1.7,NaN,NaN,NaN,NaN
2,A,NSPE,FGDP,DI__D__F,WRL_REST,AT,-0.9,0.0,-2.0,-8.8,2.4,1.2,-5.3,-3.4,2.8,NaN
3,A,NSPE,FGDP,DI__D__F,WRL_REST,BE,4.8,-2.3,5.1,12.4,1.0,5.0,2.2,1.3,2.0,NaN
4,A,NSPE,FGDP,DI__D__F,WRL_REST,BG,3.0,0.8,4.4,1.9,3.1,1.7,2.7,4.8,1.7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1829,A,TOTAL,TIFDI,NAP,WRL_REST,RO,0.9,0.7,1.2,1.3,1.3,1.4,1.2,0.7,1.9,2.0
1830,A,TOTAL,TIFDI,NAP,WRL_REST,SE,2.9,1.1,2.1,2.3,3.7,1.9,2.4,3.9,4.2,9.0
1831,A,TOTAL,TIFDI,NAP,WRL_REST,SI,-0.4,1.3,2.3,1.7,1.3,1.5,1.9,0.7,2.6,2.3
1832,A,TOTAL,TIFDI,NAP,WRL_REST,SK,-0.5,-0.2,0.1,0.5,2.8,0.9,1.2,-1.0,0.9,1.4
1833,A,TOTAL,TIFDI,NAP,WRL_REST,UK,1.8,-1.4,-0.5,3.3,3.5,1.9,0.3,NaN,NaN,NaN

In [26]:
my_filter_9 = {'geo':'ES', 'indic_bp':'SGDP', 'fdi_item':'DI__D__F'}
data9 = eurostat.get_data_df('bop_fdi6_ind', filter_pars=my_filter_9)
data9

,freq,entity,indic_bp,fdi_item,partner,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,NSPE,SGDP,DI__D__F,BR,ES,NaN,NaN,NaN,NaN,NaN,0.2,0.2,0.1,0.2,NaN
1,A,NSPE,SGDP,DI__D__F,CA,ES,NaN,NaN,NaN,NaN,NaN,0.1,0.1,0.1,0.1,NaN
2,A,NSPE,SGDP,DI__D__F,CH,ES,NaN,NaN,NaN,NaN,NaN,1.4,1.4,2.0,2.0,NaN
3,A,NSPE,SGDP,DI__D__F,CN_X_HK,ES,NaN,NaN,NaN,NaN,NaN,0.2,0.1,0.2,0.1,NaN
4,A,NSPE,SGDP,DI__D__F,EXT_EU27_2020,ES,NaN,NaN,NaN,NaN,NaN,15.6,15.6,18.4,17.0,NaN
5,A,NSPE,SGDP,DI__D__F,EXT_EU28,ES,NaN,NaN,NaN,NaN,NaN,9.3,9.3,NaN,NaN,NaN
6,A,NSPE,SGDP,DI__D__F,HK,ES,NaN,NaN,NaN,NaN,NaN,0.1,0.2,0.3,0.1,NaN
7,A,NSPE,SGDP,DI__D__F,IN,ES,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN
8,A,NSPE,SGDP,DI__D__F,JP,ES,NaN,NaN,NaN,NaN,NaN,0.5,0.5,0.6,0.6,NaN
9,A,NSPE,SGDP,DI__D__F,RU,ES,NaN,NaN,NaN,NaN,NaN,0.3,0.3,0.3,0.3,NaN
10,A,NSPE,SGDP,DI__D__F,US,ES,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.2,2.0,NaN
11,A,NSPE,SGDP,DI__D__F,WRL_REST,ES,45.4,46.9,47.1,47.2,48.0,50.1,51.0,58.1,57.7,56.5
12,A,TOTAL,SGDP,DI__D__F,WRL_REST,ES,46.1,47.6,47.8,50.4,50.4,54.6,55.5,62.7,61.7,60.0

## **10. Investments outside the EU by EU investors (% of GDP)**
This indicator shows the value of investment stocks held by multinational enterprises in the economy of countries other than the reporting country. It is divided by GDP to allow comparisons across countries.

In [27]:
my_filter_10 = {'geo':'ES', 'indic_bp':'SGDP', 'fdi_item':'DO__D__F'}
data10 = eurostat.get_data_df('bop_fdi6_ind', filter_pars=my_filter_10)
data10

,freq,entity,indic_bp,fdi_item,partner,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,NSPE,SGDP,DO__D__F,BR,ES,NaN,NaN,NaN,NaN,NaN,4.3,4.6,3.5,2.8,NaN
1,A,NSPE,SGDP,DO__D__F,CA,ES,NaN,NaN,NaN,NaN,NaN,0.5,1.0,0.5,0.6,NaN
2,A,NSPE,SGDP,DO__D__F,CH,ES,NaN,NaN,NaN,NaN,NaN,0.6,0.5,0.5,0.6,NaN
3,A,NSPE,SGDP,DO__D__F,CN_X_HK,ES,NaN,NaN,NaN,NaN,NaN,0.3,0.3,0.4,0.4,NaN
4,A,NSPE,SGDP,DO__D__F,EXT_EU27_2020,ES,NaN,NaN,NaN,NaN,NaN,31.2,31.3,30.2,28.9,NaN
5,A,NSPE,SGDP,DO__D__F,EXT_EU28,ES,NaN,NaN,NaN,NaN,NaN,23.5,24.8,NaN,NaN,NaN
6,A,NSPE,SGDP,DO__D__F,HK,ES,NaN,NaN,NaN,NaN,NaN,0.2,0.1,0.1,0.1,NaN
7,A,NSPE,SGDP,DO__D__F,IN,ES,NaN,NaN,NaN,NaN,NaN,0.1,0.1,0.1,0.1,NaN
8,A,NSPE,SGDP,DO__D__F,JP,ES,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN
9,A,NSPE,SGDP,DO__D__F,RU,ES,NaN,NaN,NaN,NaN,NaN,0.1,0.0,0.0,0.1,NaN
10,A,NSPE,SGDP,DO__D__F,US,ES,NaN,NaN,NaN,NaN,NaN,6.4,6.4,6.5,5.8,NaN
11,A,NSPE,SGDP,DO__D__F,WRL_REST,ES,40.7,41.4,43.1,42.3,41.3,39.8,41.6,40.8,40.3,39.4
12,A,TOTAL,SGDP,DO__D__F,WRL_REST,ES,41.0,41.8,43.7,45.7,43.4,44.0,46.1,45.0,43.9,42.6

## **11. Trade in goods with top 5 partner countries (% of total trade in goods)**
This indicator shows the share of trade in goods with the top 5 partners in the total trade (imports and exports) of the EU.

The trade in goods partner country concentration indicator illustrates the degree of dependence of a particular country's trade in goods on just a few (five) partner countries. A higher value of this indicator signifies greater dependency on a few partner countries, whereas a lower value suggests a more diversified portfolio of partner countries.

In [28]:
data11 = eurostat.get_data_df('egi_tr3')
data11

,freq,stk_flow,unit,geo\TIME_PERIOD,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,A,EXP,PC,AL,79.3,74.1,76.0,73.6,72.6,74.9,73.1,74.9,71.9,70.1,67.5,67.9
1,A,EXP,PC,AT,51.6,50.6,50.9,51.5,52.1,51.6,51.5,50.1,51.3,51.4,51.3,50.5
2,A,EXP,PC,BA,59.5,59.2,57.8,56.4,55.5,55.7,57.7,59.0,58.6,60.4,63.5,62.8
3,A,EXP,PC,BE,58.4,57.5,58.0,58.5,57.9,57.1,57.7,58.0,57.6,57.0,59.5,56.7
4,A,EXP,PC,BG,43.4,44.6,45.0,45.5,45.6,43.8,46.0,44.8,45.1,45.6,44.2,41.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,A,TOTAL,PC,SE,43.5,43.3,43.0,43.3,43.6,43.8,44.2,43.8,44.7,44.9,45.2,44.6
113,A,TOTAL,PC,SI,51.2,49.7,49.4,49.0,49.1,48.3,47.6,47.7,48.3,48.3,50.8,52.9
114,A,TOTAL,PC,SK,56.7,56.3,56.5,57.2,56.6,56.2,56.7,56.3,56.9,56.9,56.7,56.2
115,A,TOTAL,PC,TR,34.4,33.7,33.7,34.5,33.8,32.0,32.2,31.5,31.8,32.3,35.0,34.5
116,A,TOTAL,PC,XK,51.1,47.0,49.9,49.2,50.4,49.3,47.8,47.3,46.5,45.2,45.0,48.3

In [29]:
my_filter_11 = {'geo':'ES'}
data11 = eurostat.get_data_df('egi_tr3', filter_pars=my_filter_11)
data11

,freq,stk_flow,unit,geo\TIME_PERIOD,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,A,EXP,PC,ES,47.8,47.5,47.8,48.5,49.7,48.6,48.5,49.0,49.9,48.5,48.0,49.2
1,A,IMP,PC,ES,40.8,40.7,42.4,45.2,46.4,45.4,44.8,45.1,47.1,45.7,43.0,45.5
2,A,TOTAL,PC,ES,42.3,42.7,43.6,45.1,45.9,44.7,44.1,44.0,45.7,44.4,42.1,44.1

## **12. Trade in services with top 5 partner countries (% of total trade in services)**
This indicator shows the share of trade in services with the top 5 partners in the total trade (imports and exports) of the EU.

The trade in services partner country concentration indicator illustrates the degree of dependence of a particular country's trade in services on just a few (five) partner countries. A higher value of this indicator signifies greater dependency on a few partner countries, whereas a lower value suggests a more diversified portfolio of partner countries.

In [30]:
data12 = eurostat.get_data_df('egi_tr5')
data12

,freq,stk_flow,unit,geo\TIME_PERIOD,2004,2005,2006,2007,2008,2009,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,TOTAL,PC,AT,NaN,NaN,NaN,NaN,NaN,NaN,...,54.8,55.1,55.5,55.3,54.7,54.3,53.7,54.7,53.2,53.2
1,A,TOTAL,PC,BE,NaN,NaN,NaN,NaN,NaN,NaN,...,56.2,57.8,55.5,56.0,55.9,56.2,55.6,56.8,54.6,53.6
2,A,TOTAL,PC,BG,NaN,NaN,NaN,NaN,NaN,NaN,...,40.6,38.7,34.9,34.5,32.9,32.8,33.5,34.1,34.5,33.1
3,A,TOTAL,PC,CY,NaN,NaN,NaN,NaN,56.0,57.8,...,51.5,44.7,NaN,50.8,48.9,48.9,43.5,41.8,40.8,40.8
4,A,TOTAL,PC,CZ,NaN,NaN,NaN,NaN,NaN,NaN,...,44.8,46.0,44.5,45.4,44.5,42.6,44.1,44.8,43.8,41.9
5,A,TOTAL,PC,DE,NaN,NaN,NaN,NaN,NaN,NaN,...,42.3,42.3,42.7,42.8,42.2,41.1,40.9,41.6,41.9,40.4
6,A,TOTAL,PC,DK,NaN,NaN,NaN,NaN,NaN,NaN,...,45.4,45.3,46.0,47.3,47.0,46.9,45.2,43.1,41.5,40.1
7,A,TOTAL,PC,EE,NaN,NaN,NaN,NaN,NaN,NaN,...,52.2,50.8,49.2,48.1,48.0,46.2,45.2,53.0,45.7,38.1
8,A,TOTAL,PC,EL,NaN,NaN,NaN,NaN,NaN,NaN,...,50.0,50.2,36.4,36.2,35.6,33.2,32.7,33.0,34.4,35.7
9,A,TOTAL,PC,ES,NaN,NaN,NaN,NaN,NaN,NaN,...,48.4,48.3,47.6,47.4,47.5,47.9,47.8,47.9,46.6,47.8
10,A,TOTAL,PC,EU27_2020,NaN,NaN,NaN,NaN,NaN,NaN,...,57.4,58.1,56.6,59.5,58.2,58.2,57.7,60.4,63.6,62.8
11,A,TOTAL,PC,FI,NaN,NaN,NaN,NaN,NaN,NaN,...,45.3,45.3,43.8,44.0,41.6,42.8,41.7,46.7,48.3,46.9
12,A,TOTAL,PC,FR,NaN,NaN,NaN,NaN,NaN,NaN,...,45.6,45.8,45.5,45.1,46.6,45.8,44.8,44.6,43.9,44.5
13,A,TOTAL,PC,HR,NaN,NaN,NaN,NaN,NaN,NaN,...,46.6,47.0,46.9,45.9,44.1,46.9,44.1,44.3,44.7,46.7
14,A,TOTAL,PC,HU,NaN,NaN,NaN,NaN,NaN,NaN,...,48.6,48.5,49.5,48.0,47.5,46.7,48.3,50.7,45.8,47.2
15,A,TOTAL,PC,IE,NaN,NaN,NaN,NaN,NaN,NaN,...,54.3,52.0,NaN,NaN,49.7,NaN,NaN,52.8,NaN,55.3
16,A,TOTAL,PC,IT,NaN,NaN,NaN,NaN,43.5,42.1,...,43.9,43.8,43.2,43.8,42.9,43.0,41.7,44.0,43.0,41.6
17,A,TOTAL,PC,LT,55.7,53.9,54.7,55.4,54.1,53.0,...,50.5,50.8,44.1,41.0,40.2,39.5,38.1,38.4,36.8,36.8
18,A,TOTAL,PC,LU,NaN,NaN,NaN,NaN,NaN,NaN,...,56.0,57.2,56.5,57.8,59.0,59.5,59.2,59.6,59.6,60.6
19,A,TOTAL,PC,LV,38.2,36.3,35.8,35.1,33.8,34.6,...,35.2,43.0,41.7,39.9,40.7,40.3,41.3,38.2,37.2,37.8
20,A,TOTAL,PC,MT,NaN,NaN,NaN,NaN,NaN,NaN,...,28.9,23.5,33.3,44.8,45.1,45.7,45.5,49.0,48.0,52.3
21,A,TOTAL,PC,NL,NaN,NaN,NaN,NaN,NaN,NaN,...,48.4,50.9,47.8,51.0,47.1,NaN,NaN,53.0,54.8,52.4
22,A,TOTAL,PC,PL,NaN,NaN,NaN,NaN,NaN,NaN,...,47.8,48.3,48.9,49.3,48.9,48.8,49.4,51.3,50.1,47.8
23,A,TOTAL,PC,PT,NaN,NaN,NaN,NaN,NaN,NaN,...,53.8,53.4,54.9,56.3,55.2,56.3,57.1,57.8,56.1,53.7
24,A,TOTAL,PC,RO,NaN,NaN,NaN,NaN,NaN,NaN,...,51.8,50.4,48.6,49.6,49.9,50.3,50.6,51.1,47.8,46.9
25,A,TOTAL,PC,SE,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,48.5,48.4,46.4,47.3,46.4,44.7,45.2,44.6,45.6
26,A,TOTAL,PC,SI,NaN,NaN,NaN,NaN,NaN,NaN,...,56.2,56.6,54.7,53.5,53.5,52.9,52.7,52.5,50.7,49.7
27,A,TOTAL,PC,SK,NaN,NaN,NaN,NaN,NaN,NaN,...,57.2,55.1,55.0,53.7,51.8,51.7,52.0,51.4,49.0,48.1

In [31]:
my_filter_12 = {'geo':'ES'}
data12 = eurostat.get_data_df('egi_tr5', filter_pars=my_filter_12)
data12

,freq,stk_flow,unit,geo\TIME_PERIOD,2004,2005,2006,2007,2008,2009,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,TOTAL,PC,ES,None,None,None,None,None,None,...,48.4,48.3,47.6,47.4,47.5,47.9,47.8,47.9,46.6,47.8

## **13. Employment supported by EU exports (% of total employment)**
This indicator shows the share of employment in the EU and individual EU countries supported by EU exports.

The exports, which are accounted for, are extra-EU exports, meaning trade between EU countries is not considered. These shares include not only employment in enterprises that are directly exporting, but also of those enterprises involved in the production of exported products.

In [32]:
data13 = eurostat.get_data_df('egi_em3')
data13

,freq,unit,geo\TIME_PERIOD,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,A,PC,AT,11.5,12.2,13.0,12.8,12.9,13.1,12.9,12.8,13.1,13.4,13.2,13.6
1,A,PC,BE,16.0,15.9,16.3,17.2,17.1,16.7,16.4,16.2,15.9,15.9,15.2,15.9
2,A,PC,BG,16.2,17.5,18.9,21.3,21.2,21.9,21.1,20.8,20.1,21.4,21.1,23.3
3,A,PC,CY,12.2,13.0,14.0,16.2,16.5,16.7,17.1,17.3,17.0,17.0,18.4,18.6
4,A,PC,CZ,13.0,14.4,16.7,17.0,17.0,16.8,16.5,16.6,16.0,15.7,15.4,15.4
5,A,PC,DE,13.6,14.4,15.8,15.8,15.9,16.8,16.3,16.4,15.7,15.6,14.6,15.2
6,A,PC,DK,13.3,13.7,14.7,14.6,14.7,15.1,14.7,15.3,15.5,15.8,14.9,15.2
7,A,PC,EE,16.1,16.5,16.6,17.5,17.0,15.5,15.6,16.3,15.9,16.6,16.0,17.7
8,A,PC,EL,7.1,8.4,9.7,10.0,10.0,9.8,9.6,9.9,11.1,11.0,10.7,12.0
9,A,PC,ES,10.1,11.2,12.7,12.7,12.4,12.5,12.5,12.2,11.7,12.1,11.5,12.8
10,A,PC,EU27_2020,11.9,12.8,14.1,14.4,14.4,14.8,14.6,14.6,14.3,14.4,13.8,14.5
11,A,PC,FI,14.5,14.4,14.7,14.3,13.8,14.2,13.8,14.1,13.8,13.9,13.5,14.4
12,A,PC,FR,9.7,10.6,11.3,11.6,11.8,12.3,12.2,12.0,12.0,12.2,11.1,11.7
13,A,PC,HR,9.5,11.6,12.7,11.7,12.9,10.2,9.7,9.8,9.2,9.2,9.3,10.2
14,A,PC,HU,13.6,15.1,15.3,15.5,15.2,15.8,16.0,15.6,15.2,14.9,15.1,15.9
15,A,PC,IE,26.8,23.4,25.8,25.6,23.7,25.3,24.9,25.8,27.0,22.8,23.6,26.6
16,A,PC,IT,9.8,10.7,12.1,12.3,12.4,13.0,12.7,13.0,12.7,13.0,12.7,13.4
17,A,PC,LT,15.4,16.2,17.5,18.2,19.4,16.9,16.6,17.7,16.3,17.7,18.1,17.6
18,A,PC,LU,23.6,24.7,26.2,26.3,26.8,26.3,27.1,24.1,24.1,24.5,25.4,25.2
19,A,PC,LV,15.8,16.5,18.3,17.8,18.0,17.7,16.9,17.2,17.1,18.0,17.9,17.1
20,A,PC,MT,19.2,21.7,24.4,22.6,20.6,21.1,21.1,24.6,24.7,24.5,23.5,19.4
21,A,PC,NL,13.8,14.7,15.6,15.9,15.6,18.6,17.4,17.6,17.5,17.3,16.4,17.2
22,A,PC,PL,12.0,13.0,14.1,14.5,14.3,14.4,15.0,15.2,14.5,14.8,15.0,15.5
23,A,PC,PT,8.3,10.2,12.4,13.2,13.1,13.0,12.4,12.8,12.2,12.2,11.9,12.7
24,A,PC,RO,9.8,11.4,13.7,15.5,16.3,15.6,15.9,14.7,14.6,14.8,13.9,14.6
25,A,PC,SE,16.0,16.0,16.7,15.4,15.5,14.8,14.2,13.8,14.5,14.8,14.1,14.1
26,A,PC,SI,15.2,15.7,16.2,16.3,16.8,17.2,17.3,17.3,16.8,16.7,16.7,16.8
27,A,PC,SK,12.7,14.2,16.1,16.4,15.8,15.3,15.8,15.8,16.1,15.5,15.4,15.9

In [33]:
my_filter_13 = {'geo':'ES'}
data13 = eurostat.get_data_df('egi_em3', filter_pars=my_filter_13)
data13

,freq,unit,geo\TIME_PERIOD,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,A,PC,ES,10.1,11.2,12.7,12.7,12.4,12.5,12.5,12.2,11.7,12.1,11.5,12.8

## **14. Value added supported by EU exports (% of total value added) (FIGARO application)**
This indicator shows the share of the value added in the EU and individual EU countries supported by EU exports.

The exports, which are accounted for, are extra-EU exports, meaning trade between EU countries is not considered. These shares include not only the value added by enterprises that are directly exporting, but also the value added by those enterprises providing goods or services involved in the production of exported products.

In [34]:
data14 = eurostat.get_data_df('egi_va2')
data14

,freq,unit,geo\TIME_PERIOD,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,A,PC,AT,13.5,14.3,15.3,15.0,15.2,15.5,15.3,15.2,15.5,15.6,15.1,16.0
1,A,PC,BE,18.4,17.4,17.8,19.2,19.4,19.3,19.0,18.9,18.6,18.6,17.8,19.0
2,A,PC,BG,15.8,17.9,19.4,21.2,20.8,21.2,21.3,21.0,20.2,20.9,20.0,22.4
3,A,PC,CY,16.8,18.4,19.2,23.4,24.3,25.4,26.3,26.1,25.5,25.3,28.5,28.1
4,A,PC,CZ,13.2,14.5,17.0,17.3,17.7,17.5,17.1,17.0,16.1,15.7,15.1,15.2
5,A,PC,DE,16.3,17.3,18.8,18.7,19.0,19.9,19.4,19.5,18.5,18.3,16.9,17.9
6,A,PC,DK,17.2,17.5,19.2,19.2,19.7,19.8,18.9,20.0,20.0,20.7,19.9,21.2
7,A,PC,EE,20.0,21.1,20.6,21.5,21.3,19.0,18.4,19.1,18.5,19.0,18.2,20.9
8,A,PC,EL,8.7,10.1,11.0,10.9,11.5,10.9,10.5,11.6,13.2,12.9,12.6,14.3
9,A,PC,ES,10.0,11.5,13.0,12.8,12.7,12.9,12.7,12.4,12.0,12.3,11.6,13.0
10,A,PC,EU27_2020,13.8,14.7,16.0,16.1,16.3,17.3,16.8,17.1,16.8,16.7,15.9,17.1
11,A,PC,FI,17.1,16.6,16.5,16.2,15.8,16.3,15.8,16.6,16.2,16.3,15.4,16.9
12,A,PC,FR,10.8,11.7,12.7,12.9,13.1,14.0,13.6,13.5,13.5,13.7,12.2,13.0
13,A,PC,HR,9.7,10.8,11.8,11.1,12.2,10.0,9.6,9.7,9.3,9.3,9.6,10.3
14,A,PC,HU,15.7,17.7,18.3,18.7,18.4,19.4,19.4,18.4,17.5,16.6,16.8,17.8
15,A,PC,IE,36.9,31.7,33.8,33.0,32.7,40.5,40.3,43.6,45.5,38.0,40.5,46.9
16,A,PC,IT,10.0,11.0,12.3,12.6,12.7,13.6,13.3,13.8,13.5,13.7,13.2,14.2
17,A,PC,LT,18.5,20.5,22.2,23.1,23.4,20.3,19.7,21.2,19.8,21.0,21.1,20.6
18,A,PC,LU,29.4,30.7,32.3,32.6,33.1,32.7,33.3,31.0,30.7,30.3,32.3,33.0
19,A,PC,LV,17.4,18.3,20.3,19.4,19.2,19.0,18.2,18.3,18.1,18.6,17.9,17.5
20,A,PC,MT,24.9,29.7,32.2,29.1,28.5,28.7,27.8,34.6,35.4,32.2,30.1,18.9
21,A,PC,NL,17.7,18.6,19.7,20.2,19.7,22.8,21.1,21.4,21.1,20.7,19.6,20.8
22,A,PC,PL,13.3,14.4,15.8,15.9,15.4,15.6,16.1,16.4,15.7,16.0,16.5,17.3
23,A,PC,PT,8.1,10.0,11.9,12.6,12.5,12.4,11.7,12.2,11.6,11.5,10.9,11.8
24,A,PC,RO,10.8,13.7,13.8,15.5,15.7,16.0,16.0,15.0,14.2,14.0,13.0,14.1
25,A,PC,SE,19.3,19.2,19.7,18.5,18.8,18.6,17.7,17.4,18.1,18.6,17.6,17.9
26,A,PC,SI,15.8,17.0,17.6,17.9,18.8,19.3,19.0,19.6,18.5,18.3,18.4,18.7
27,A,PC,SK,13.2,14.6,16.5,16.8,16.8,16.0,16.0,15.6,16.2,16.1,15.7,16.3

In [35]:
my_filter_14 = {'geo':'ES'}
data14 = eurostat.get_data_df('egi_va2', filter_pars=my_filter_14)
data14

,freq,unit,geo\TIME_PERIOD,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,A,PC,ES,10.0,11.5,13.0,12.8,12.7,12.9,12.7,12.4,12.0,12.3,11.6,13.0

## **15. Rate of return on direct investment abroad (% of investments)**
This indicators shows the rate of return that the enterprises from the domestic EU markets have had on their investments abroad.

In [36]:
# Variable: Entity
# Value: [TOTAL] Total
# Value: [NSPE] Non-special purpose entities (or Operating units)

# Variable: indic_bp
# Value: [FGDP] GDP (flows in % of GDP)
# Value: [SGDP] GDP (stocks in % of GDP)
# Value: [IPOS] Rate of return on direct investment (FDI income / FDI stocks)
# Value: [PCPOS] FDI stocks (in % of extra EU FDI stocks)
# Value: [TIFDI] Market integration - Foreign Direct Investment intensity - Average value of inward and outward Foreign Direct Investment flows divided by GDP, multiplied by 100

# Variable: fdi_item
# Value: [DO__D__F] Direct investment abroad (DIA)
# Value: [DI__D__F] Direct investment in the reporting economy (DIRE)
# Value: [NAP] Not applicable

In [37]:
data15 = eurostat.get_data_df('bop_fdi6_ind')
data15

,freq,entity,indic_bp,fdi_item,partner,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,NSPE,FGDP,DI__D__F,EXT_EU27_2020,EU27_2020,0.8,0.7,2.7,1.3,0.7,1.8,0.7,NaN,NaN,NaN
1,A,NSPE,FGDP,DI__D__F,EXT_EU28,EU28,0.9,0.5,2.1,1.6,0.4,1.7,NaN,NaN,NaN,NaN
2,A,NSPE,FGDP,DI__D__F,WRL_REST,AT,-0.9,0.0,-2.0,-8.8,2.4,1.2,-5.3,-3.4,2.8,NaN
3,A,NSPE,FGDP,DI__D__F,WRL_REST,BE,4.8,-2.3,5.1,12.4,1.0,5.0,2.2,1.3,2.0,NaN
4,A,NSPE,FGDP,DI__D__F,WRL_REST,BG,3.0,0.8,4.4,1.9,3.1,1.7,2.7,4.8,1.7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1829,A,TOTAL,TIFDI,NAP,WRL_REST,RO,0.9,0.7,1.2,1.3,1.3,1.4,1.2,0.7,1.9,2.0
1830,A,TOTAL,TIFDI,NAP,WRL_REST,SE,2.9,1.1,2.1,2.3,3.7,1.9,2.4,3.9,4.2,9.0
1831,A,TOTAL,TIFDI,NAP,WRL_REST,SI,-0.4,1.3,2.3,1.7,1.3,1.5,1.9,0.7,2.6,2.3
1832,A,TOTAL,TIFDI,NAP,WRL_REST,SK,-0.5,-0.2,0.1,0.5,2.8,0.9,1.2,-1.0,0.9,1.4
1833,A,TOTAL,TIFDI,NAP,WRL_REST,UK,1.8,-1.4,-0.5,3.3,3.5,1.9,0.3,NaN,NaN,NaN

In [38]:
my_filter_15 = {'geo':'ES', 'indic_bp':'IPOS', 'fdi_item':'DO__D__F'}
data15 = eurostat.get_data_df('bop_fdi6_ind', filter_pars=my_filter_15)
data15

,freq,entity,indic_bp,fdi_item,partner,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,TOTAL,IPOS,DO__D__F,BR,ES,NaN,NaN,NaN,NaN,NaN,NaN,7.9,NaN,NaN,11.4
1,A,TOTAL,IPOS,DO__D__F,CA,ES,1.8,6.9,7.8,4.5,5.2,NaN,NaN,NaN,NaN,NaN
2,A,TOTAL,IPOS,DO__D__F,CH,ES,6.1,NaN,NaN,NaN,NaN,NaN,3.7,10.0,6.5,7.1
3,A,TOTAL,IPOS,DO__D__F,CN_X_HK,ES,NaN,NaN,NaN,NaN,NaN,NaN,7.4,6.5,8.7,8.2
4,A,TOTAL,IPOS,DO__D__F,EXT_EU27_2020,ES,NaN,NaN,NaN,6.3,NaN,NaN,6.2,4.8,7.0,7.2
5,A,TOTAL,IPOS,DO__D__F,EXT_EU28,ES,NaN,6.6,6.4,6.7,6.4,5.6,6.2,NaN,NaN,NaN
6,A,TOTAL,IPOS,DO__D__F,HK,ES,NaN,NaN,NaN,NaN,NaN,NaN,8.7,9.6,12.9,NaN
7,A,TOTAL,IPOS,DO__D__F,IN,ES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.5,3.6
8,A,TOTAL,IPOS,DO__D__F,JP,ES,NaN,NaN,NaN,NaN,NaN,NaN,7.1,1.7,2.9,3.4
9,A,TOTAL,IPOS,DO__D__F,RU,ES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,A,TOTAL,IPOS,DO__D__F,UK,ES,9.3,NaN,NaN,5.0,NaN,NaN,6.4,1.2,0.7,3.6
11,A,TOTAL,IPOS,DO__D__F,US,ES,NaN,2.8,2.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,A,TOTAL,IPOS,DO__D__F,WRL_REST,ES,NaN,6.2,6.1,6.0,6.0,5.8,6.7,5.0,6.9,7.1

## **16. Rate of return on direct investment in the reporting economy (% of investments)**
This indicators shows the rate of return that the enterprises from the non-EU (foreign) markets have had on their investments in the EU.

In [39]:
my_filter_16 = {'geo':'ES', 'indic_bp':'IPOS', 'fdi_item':'DI__D__F'}
data16 = eurostat.get_data_df('bop_fdi6_ind', filter_pars=my_filter_16)
data16

,freq,entity,indic_bp,fdi_item,partner,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,TOTAL,IPOS,DI__D__F,BR,ES,NaN,7.4,NaN,NaN,0.9,2.2,NaN,NaN,NaN,NaN
1,A,TOTAL,IPOS,DI__D__F,CA,ES,6.7,8.7,10.8,1.4,2.5,NaN,NaN,NaN,NaN,NaN
2,A,TOTAL,IPOS,DI__D__F,CH,ES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN
3,A,TOTAL,IPOS,DI__D__F,CN_X_HK,ES,NaN,0.0,NaN,NaN,NaN,NaN,8.1,NaN,NaN,NaN
4,A,TOTAL,IPOS,DI__D__F,EXT_EU27_2020,ES,5.6,3.4,4.2,NaN,3.9,3.1,NaN,2.9,2.7,2.8
5,A,TOTAL,IPOS,DI__D__F,EXT_EU28,ES,5.3,3.3,3.8,4.0,4.0,3.0,4.7,NaN,NaN,NaN
6,A,TOTAL,IPOS,DI__D__F,HK,ES,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,A,TOTAL,IPOS,DI__D__F,IN,ES,NaN,NaN,NaN,64.9,27.1,NaN,NaN,NaN,NaN,NaN
8,A,TOTAL,IPOS,DI__D__F,JP,ES,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN
9,A,TOTAL,IPOS,DI__D__F,RU,ES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,A,TOTAL,IPOS,DI__D__F,UK,ES,6.0,3.6,4.7,NaN,3.6,NaN,NaN,2.5,0.8,1.2
11,A,TOTAL,IPOS,DI__D__F,US,ES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,A,TOTAL,IPOS,DI__D__F,WRL_REST,ES,NaN,3.7,3.9,3.8,4.2,3.2,4.3,3.2,3.8,3.7

## **17. Trade of intermediate goods (% of total trade in goods)**
This indicator shows the share of intermediate goods in the trade of the EU and its members.

It is calculated as percentage in the total trade of intermediate goods and half of the dual-use categories including intermediate goods. Total trade is the sum of imports and exports.

In [40]:
data17 = eurostat.get_data_df('egi_tr2')
data17

,freq,stk_flow,unit,geo\TIME_PERIOD,2017,2018,2019,2020,2021,2022,2023
0,A,EXP,MIO_EUR,AT,81064.8,84901.5,84417.7,77863.0,92503.8,111616.6,109313.0
1,A,EXP,MIO_EUR,BE,198906.5,216817.4,213963.3,198646.4,256525.6,372924.4,304998.8
2,A,EXP,MIO_EUR,BG,16098.6,16905.4,17274.1,16650.2,21718.7,28950.5,25990.0
3,A,EXP,MIO_EUR,CY,568.2,715.7,552.9,497.3,673.8,933.3,789.4
4,A,EXP,MIO_EUR,CZ,80005.2,83785.6,85070.7,77171.9,92273.2,111306.8,110461.7
...,...,...,...,...,...,...,...,...,...,...,...
163,A,TOTAL,PC,PT,53.9,53.9,52.3,53.0,55.4,57.6,54.9
164,A,TOTAL,PC,RO,62.5,61.7,60.8,59.3,60.8,62.3,60.0
165,A,TOTAL,PC,SE,52.3,52.3,51.3,49.9,51.9,55.3,53.2
166,A,TOTAL,PC,SI,53.7,53.5,52.2,52.3,54.6,63.5,64.7
167,A,TOTAL,PC,SK,52.1,52.4,51.4,50.0,52.8,54.4,51.6

In [41]:
my_filter_17 = {'geo':'ES'}
data17 = eurostat.get_data_df('egi_tr2', filter_pars=my_filter_17)
data17

,freq,stk_flow,unit,geo\TIME_PERIOD,2017,2018,2019,2020,2021,2022,2023
0,A,EXP,MIO_EUR,ES,121675.6,128902.6,128294.7,113320.1,145054.1,191467.7,179232.0
1,A,EXP,PC,ES,45.0,46.1,44.8,43.7,46.7,50.5,47.5
2,A,IMP,MIO_EUR,ES,165825.3,179822.8,178773.1,151930.0,199072.0,279921.4,244745.5
3,A,IMP,PC,ES,55.0,56.3,55.5,54.9,57.5,61.0,57.7
4,A,TOTAL,MIO_EUR,ES,287500.9,308725.4,307067.7,265250.1,344126.1,471389.1,423977.4
5,A,TOTAL,PC,ES,50.2,51.6,50.5,49.5,52.4,56.2,52.9

## **18. Trade of intermediate services (% of total trade in services)**
This indicator shows the intermediate services as a share of the total services trade for the EU and its countries. It is calculated as percentage of the intermediate services in the total trade volume (sum of exports plus imports).

Intermediate services - as well as intermediate goods - are of particular relevance for global value chains (GVCs) analysis, as they serve as inputs to other economic activities. The classification by broad economic categories (BEC Rev.5) is used to distinguish intermediate services from final use services.

In [42]:
data18 = eurostat.get_data_df('egi_tr4')
data18

,freq,stk_flow,unit,geo\TIME_PERIOD,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,TOTAL,PC,AT,59.2,61.9,62.7,67.3,68.5,68.4,68.8,69.4,70.3,70.2,75.9,77.8,72.5
1,A,TOTAL,PC,BE,74.0,72.9,74.4,74.7,75.1,79.4,79.0,79.0,78.4,78.3,80.5,80.7,80.4
2,A,TOTAL,PC,BG,49.3,48.9,51.9,50.3,56.0,59.4,57.2,54.3,53.8,56.5,66.4,65.5,65.0
3,A,TOTAL,PC,CY,59.5,59.2,58.7,59.6,61.9,65.7,65.9,65.5,65.9,70.9,79.1,77.8,76.0
4,A,TOTAL,PC,CZ,66.8,68.4,70.0,72.1,72.6,72.6,72.2,71.9,72.2,73.0,78.4,79.9,76.8
5,A,TOTAL,PC,DE,67.9,68.8,68.8,71.1,71.8,72.7,73.1,72.7,73.2,74.0,81.5,81.8,78.1
6,A,TOTAL,PC,DK,80.3,80.5,80.2,80.3,79.8,79.1,77.4,76.7,77.0,79.0,85.1,86.2,87.0
7,A,TOTAL,PC,EE,65.4,65.5,66.4,64.1,63.4,62.9,63.1,63.6,63.7,62.9,74.1,78.5,74.8
8,A,TOTAL,PC,EL,67.7,64.2,62.3,57.8,56.7,58.3,56.4,58.8,59.5,58.1,75.8,72.3,68.0
9,A,TOTAL,PC,ES,51.2,52.5,51.8,50.7,51.6,52.4,52.6,51.5,51.5,52.2,73.2,68.6,57.7
10,A,TOTAL,PC,EU27_2020,70.6,70.9,70.6,71.5,73.3,74.4,74.7,74.3,74.3,76.0,82.5,82.1,79.0
11,A,TOTAL,PC,FI,75.6,75.1,71.6,75.0,74.5,75.3,75.7,75.3,76.6,78.0,86.7,88.0,83.3
12,A,TOTAL,PC,FR,68.1,68.6,69.1,70.2,71.6,72.5,72.6,72.2,72.2,72.3,79.0,78.7,76.5
13,A,TOTAL,PC,HR,40.9,40.1,39.2,35.5,40.9,35.7,34.4,33.4,33.6,34.3,46.9,38.1,35.9
14,A,TOTAL,PC,HU,69.2,71.0,72.2,74.1,73.4,72.7,72.1,71.0,70.9,70.5,79.2,77.7,71.3
15,A,TOTAL,PC,IE,75.1,75.9,74.5,73.4,74.9,77.6,80.5,79.6,77.5,81.6,82.7,79.3,77.8
16,A,TOTAL,PC,IT,59.7,59.3,59.1,59.0,58.3,58.4,58.5,58.1,58.8,58.5,70.7,71.1,63.8
17,A,TOTAL,PC,LT,70.5,73.2,73.9,75.8,77.3,76.2,77.1,78.6,79.2,81.6,88.1,89.0,85.7
18,A,TOTAL,PC,LU,59.8,59.3,60.3,61.1,62.4,63.9,65.1,66.2,67.5,68.1,71.3,72.0,72.8
19,A,TOTAL,PC,LV,67.8,68.5,68.2,67.5,68.0,66.5,63.6,64.8,63.5,64.6,70.5,71.7,68.4
20,A,TOTAL,PC,MT,48.2,63.2,66.1,66.1,65.8,62.2,61.3,60.1,59.5,61.1,62.9,57.9,57.1
21,A,TOTAL,PC,NL,73.4,74.3,72.1,75.8,82.2,82.2,81.9,82.5,83.6,83.7,85.1,84.9,82.6
22,A,TOTAL,PC,PL,66.2,66.8,66.6,69.9,71.2,71.5,72.0,72.2,73.5,74.3,80.1,81.0,78.1
23,A,TOTAL,PC,PT,49.5,50.1,47.2,49.1,49.3,49.5,49.3,47.5,46.7,47.4,61.5,61.1,51.9
24,A,TOTAL,PC,RO,68.2,68.4,68.7,77.3,76.7,76.1,74.8,71.0,71.1,70.6,76.3,71.3,69.2
25,A,TOTAL,PC,SE,70.4,70.5,69.6,71.2,70.8,71.1,70.0,68.6,69.8,70.9,76.1,75.0,73.7
26,A,TOTAL,PC,SI,54.8,55.1,55.7,54.5,55.9,56.1,57.2,59.8,60.7,60.9,71.0,69.9,66.8
27,A,TOTAL,PC,SK,61.2,60.7,61.6,67.6,68.0,66.7,67.3,67.7,69.0,68.8,77.4,79.1,77.9

In [43]:
my_filter_18 = {'geo':'ES'}
data18 = eurostat.get_data_df('egi_tr4', filter_pars=my_filter_18)
data18

,freq,stk_flow,unit,geo\TIME_PERIOD,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,TOTAL,PC,ES,51.2,52.5,51.8,50.7,51.6,52.4,52.6,51.5,51.5,52.2,73.2,68.6,57.7

## **19. Value added in foreign controlled enterprises (% of total value added)**
This indicator shows the share of value added generated by foreign-controlled enterprises in total value added generated by enterprises.

In [44]:
# Variable: nace_r2
# Value: [B-N_‚ÄãS95_‚ÄãX_‚ÄãK] Total business economy; repair of computers, personal and household goods; except financial and insurance activities

# Variable: indic_sb
# [V12150] Value added at factor cost - million euro

# Variable: unit
# [PCH_‚Äã1Y] Percentage change (t/t-1)
# [PC_‚ÄãTOT] Percentage of total

In [45]:
data19 = eurostat.get_data_df('egi_va1')
data19

,freq,nace_r2,indic_sb,unit,geo\TIME_PERIOD,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,A,B-N_S95_X_K,V12150,PCH_1Y,AT,NaN,-4.45,9.62,1.23,-1.80,-0.76,6.04,2.24,3.12,-1.66,2.45,-2.93,-4.12
1,A,B-N_S95_X_K,V12150,PCH_1Y,BA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.27,5.24,5.92,10.76,NaN,NaN
2,A,B-N_S95_X_K,V12150,PCH_1Y,BE,NaN,NaN,NaN,-3.51,-4.86,-0.46,-1.26,-1.53,-6.05,-3.06,7.21,-4.99,1.08
3,A,B-N_S95_X_K,V12150,PCH_1Y,BG,NaN,1.64,12.44,7.92,-1.58,-1.92,6.07,-1.03,0.43,-1.98,6.02,-4.07,-2.28
4,A,B-N_S95_X_K,V12150,PCH_1Y,CY,NaN,11.27,21.50,17.18,2.41,17.52,1.82,14.29,4.30,-0.82,-0.60,-4.64,0.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,A,B-N_S95_X_K,V12150,PC_TOT,RO,39.34,40.34,42.71,40.75,45.47,45.05,43.90,43.87,43.97,44.18,44.72,42.61,42.47
60,A,B-N_S95_X_K,V12150,PC_TOT,SE,26.86,28.88,28.37,27.87,27.78,26.59,27.08,27.12,26.47,26.82,27.22,26.51,26.23
61,A,B-N_S95_X_K,V12150,PC_TOT,SI,16.50,16.46,17.05,19.21,20.36,21.94,24.09,26.31,27.28,27.23,27.99,27.83,27.79
62,A,B-N_S95_X_K,V12150,PC_TOT,SK,41.65,43.31,36.47,38.23,39.93,35.44,43.59,45.83,48.07,48.14,46.99,46.31,45.76
63,A,B-N_S95_X_K,V12150,PC_TOT,UK,28.72,28.60,29.05,29.28,30.08,29.40,29.92,29.62,27.99,NaN,NaN,NaN,NaN

In [46]:
my_filter_19 = {'geo':'ES'}
data19 = eurostat.get_data_df('egi_va1', filter_pars=my_filter_19)
data19

,freq,nace_r2,indic_sb,unit,geo\TIME_PERIOD,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,A,B-N_S95_X_K,V12150,PCH_1Y,ES,NaN,2.75,26.83,6.56,5.67,6.08,0.62,4.03,1.41,4.14,-3.63,-0.09,6.17
1,A,B-N_S95_X_K,V12150,PC_TOT,ES,13.46,13.83,17.54,18.69,19.75,20.95,21.08,21.93,22.24,23.16,22.32,22.30,23.68

## **20. Enterprises sourcing abroad (% of enterprises located in the country)**
This indicator shows the share of enterprises engaging in either outsourcing or insourcing as a share of all enterprises.

Outsourcing refers to international sourcing outside of the enterprise group, while insourcing refers to international sourcing within the enterprise group.

In [47]:
# Variable: bus_part
# Value: [TOTAL] Total
# Value: [IN_INTL] Within enterprise group abroad
# Value: [OUT_INTL] Outside enterprise group abroad

# Variable: src_act
# Value: [SRC_INTL_REF] International sourcing in the reference period

# Variable: nace_r2
# Value: [TOTAL] Total - all NACE activities

# Variable: indic_sb
# Value: [V11110] Enterprises - number

# Variable: unit
# Value: [PC_S] Standardised percentage

In [48]:
data20 = eurostat.get_data_df('egi_so1')
data20

,freq,bus_part,src_act,nace_r2,indic_sb,unit,geo\TIME_PERIOD,2007,2012,2018,2021
0,A,IN_INTL,SRC_INTL_REF,TOTAL,V11110,PC_S,AT,NaN,NaN,0.58,3.63
1,A,IN_INTL,SRC_INTL_REF,TOTAL,V11110,PC_S,BE,NaN,11.46,NaN,NaN
2,A,IN_INTL,SRC_INTL_REF,TOTAL,V11110,PC_S,BG,NaN,6.25,0.30,0.91
3,A,IN_INTL,SRC_INTL_REF,TOTAL,V11110,PC_S,CZ,3.42,NaN,NaN,NaN
4,A,IN_INTL,SRC_INTL_REF,TOTAL,V11110,PC_S,DE,11.61,NaN,1.26,1.45
...,...,...,...,...,...,...,...,...,...,...,...
67,A,TOTAL,SRC_INTL_REF,TOTAL,V11110,PC_S,PT,12.20,15.26,6.58,4.76
68,A,TOTAL,SRC_INTL_REF,TOTAL,V11110,PC_S,RO,NaN,3.28,3.70,NaN
69,A,TOTAL,SRC_INTL_REF,TOTAL,V11110,PC_S,SE,5.66,13.21,6.87,3.16
70,A,TOTAL,SRC_INTL_REF,TOTAL,V11110,PC_S,SI,19.71,NaN,NaN,NaN
71,A,TOTAL,SRC_INTL_REF,TOTAL,V11110,PC_S,SK,NaN,11.04,2.94,NaN

In [49]:
# Spain is not included in the dataset

In [50]:
my_filter_20 = {'geo':'DE'}
data20 = eurostat.get_data_df('egi_so1', filter_pars=my_filter_20)
data20

,freq,bus_part,src_act,nace_r2,indic_sb,unit,geo\TIME_PERIOD,2007,2012,2018,2021
0,A,IN_INTL,SRC_INTL_REF,TOTAL,V11110,PC_S,DE,11.61,None,1.26,1.45
1,A,OUT_INTL,SRC_INTL_REF,TOTAL,V11110,PC_S,DE,3.56,None,0.60,NaN
2,A,TOTAL,SRC_INTL_REF,TOTAL,V11110,PC_S,DE,13.23,None,1.69,1.62

## **21. CO2 footprints (Thousand tonnes)**
This indicator shows the total EU CO2 footprint.

Emissions from the consumption perspective (‚Äòfootprints‚Äô) are linked to final consumption of goods and services in the EU. This includes all emissions that occur throughout the production chain of a product that arrives in the EU for final consumption or investment ‚Äì irrespective of the industry or country where the emission occurred.

In [51]:
# Variable: indic_env
# Value: [CO2_CONS_FP] CO2 emissions - consumption perspective (footprint)
# Value: [CO2_PRD] CO2 emissions - production perspective

# Variable: unit
# Value: [THS_T] Thousand tonnes

In [52]:
data21 = eurostat.get_data_df('egi_co2_1')
data21

,freq,indic_env,unit,geo\TIME_PERIOD,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,A,CO2_CONS_FP,THS_T,EU27_2020,4209578.474,4129435.641,3887557.280,3792652.464,3672251.241,3620813.949,3635077.914,3658779.547,3698592.403,3571730.646,3178437.915,3468402.190
1,A,CO2_PRD,THS_T,EU27_2020,3666991.121,3562354.877,3489938.698,3399977.262,3251418.425,3318280.904,3326322.550,3370918.507,3316298.720,3176218.138,2814849.968,3009011.889